
service: midsomerplots-content

#plugins:
#  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: prod
  region: us-east-1

functions:
  getPlot:
    timeout: 29
    memorySize: 2048
    handler: index.handler
    events:
      - http:
          path: plot
          cors: true
          method: get

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
